name: Increment Version

on:
  workflow_dispatch:

jobs:
  adjust-version:
    runs-on: ubuntu-latest
    steps:

    - name: Bump version
      id: bump_version
      uses: robertpeteuil/increment-version-action@master
      with:
        current-version: '1.2.3'
        version-fragment: 'bug'

    - name: Do something with your bumped release version
      run: echo ${{ steps.bump_version.outputs.next-version }}


